### ISSUE TITLE
Allow for thinning and burnin

### ISSUE THREAD

**Issue by HanjoStudy** [bdemeshev/bvarr#15]
Thanks for the package, its one of the more intuitive API for a BVAR in R.
If I could ask that you add functionality for burnin and thinning in the fit (`bvar_conj_estimate`) and estimate (`bvar_conj_estimate`) of the model. 

Currently I am finding using a post processing to implement these parameter settings:

```
df_forecast <- bvar_conj_forecast(model, h = 1, output = "long", verbose = T, include = "raw", type = "prediction")
  
df_forecast %>%  
  data.frame %>% 
  set_names(c("inflation", "unemployment", "interest_rate"))  %>% 
  filter(row_number() > 1000, row_number() %% 20 == 0) %>% 
  gather(., var, value) %>% 
  ggplot(., aes(value)) + 
  geom_density() +
  facet_wrap(~var)
```
If this could easily be implemented under the hood in the MCMC function itself

**Comment by bdemeshev** [comment]
It supposed to be a big project for many types of bvar's but alas... ;)

For conjugate normal - inverse Wishart BVAR you don't need burn-in nor thinning because sampling is done directly from exact posterior distribution.

It is strongly advised to play with prior hyperparameters, because you may get much better forecasts.

Thank you for the comment! If you have any other remarks, I am here :)

**Comment by HanjoStudy** [comment]
Thanks! With a little help of google translate on the documentation, I found it

![image](https://user-images.githubusercontent.com/12710800/40108389-01a62dc4-58fb-11e8-8603-2ac755839979.png)

Ill play with the prior hyperparameters in a `expand.grid` kind of way to find the best in-sample estimates then use these in my forecast. Wish you the best for this project
